DROP TABLE IF EXISTS CUSTOMER CASCADE;

CREATE TABLE CUSTOMER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(250) NOT NULL,
  FIRSTNAME VARCHAR(250) NOT NULL,
  SURNAME VARCHAR(250) NOT NULL,
  TELEPHONE_NUMBER VARCHAR(250) NULL DEFAULT '',
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS CUSTOMER_ADDRESS CASCADE ;

CREATE TABLE CUSTOMER_ADDRESS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STREET_NAME VARCHAR(250) NOT NULL,
  CITY VARCHAR(250) NOT NULL,
  POSTCODE VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)

);

DROP TABLE IF EXISTS C_A;

CREATE TABLE C_A (
  CUSTOMER_ID INT NOT NULL,
  ADDRESS_ID INT NOT NULL,
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY(ADDRESS_ID) REFERENCES CUSTOMER_ADDRESS(ID),
  PRIMARY KEY(CUSTOMER_ID, ADDRESS_ID)
);